# .travis.yml for R, see https://docs.travis-ci.com/user/languages/r/

language: r

r_build_args: --no-build-vignettes --no-manual --no-resave-data

r_check_args: --no-build-vignettes --no-manual

notifications:
  email:
    on_success: change
    on_failure: change
