# .travis.yml for R, see https://docs.travis-ci.com/user/languages/r/

language: r

cache: packages

r_build_args: --no-build-vignettes --no-manual --no-resave-data

r_check_args: --no-build-vignettes --no-manual

warnings_are_errors: false

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  - Rscript -e 'sessionInfo()'
  - Rscript -e 'installed.packages()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change


