# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnormal <- function(x, mu, sigma) {
    .Call('GMCM_dmvnormal', PACKAGE = 'GMCM', x, mu, sigma)
}

dgmm_loglik <- function(mus, sigmas, pie, z, marginal_loglik) {
    .Call('GMCM_dgmm_loglik', PACKAGE = 'GMCM', mus, sigmas, pie, z, marginal_loglik)
}

dgmm_loglik_marginal <- function(mus, sigmas, pie, z, marginal_loglik) {
    .Call('GMCM_dgmm_loglik_marginal', PACKAGE = 'GMCM', mus, sigmas, pie, z, marginal_loglik)
}

approx_pnorm <- function(z, mu, sd) {
    .Call('GMCM_approx_pnorm', PACKAGE = 'GMCM', z, mu, sd)
}

pgmm_marginal <- function(z, mus, sigmas, pie) {
    .Call('GMCM_pgmm_marginal', PACKAGE = 'GMCM', z, mus, sigmas, pie)
}

