# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multivariate Gaussian probability density function
#' 
#' Fast simulation and evalutation of multivariate Gaussian probability
#' densities.
#' 
#' \code{dmvnormal} functions similarly to \code{dmvnorm} from the
#' \code{mvtnorm}-package.
#' 
#' @aliases dmvnormal rmvnormal
#' @param x A p times k matrix of quantiles. Each rows correspond to a
#' realization from the density and each column corresponds to a dimension.
#' @param n The number of observations to be simulated.
#' @param mu The mean vector of dimension k.
#' @param sigma The variance-covariance matrix of dimension k times k.
#' @return \code{dmvnorm} returns a 1 by p matrix of the probability densities
#' corresponding to each row of x.
#' 
#' \code{rmvnorm} returns a p by k matrix of observations from at multivariate
#' normal distribution with the given mean \code{mu} and covariance
#' \code{sigma}. Each row corresponds to an observation.
#' @author Anders Ellern Bilgrau
#' @seealso \code{dmvnorm} and \code{rmvnorm} in the \code{mvtnorm}-package.
#' @keywords ~kwd1 ~kwd2
#' @examples
#' 
#' GMCM:::dmvnormal(x = matrix(rnorm(300), 100, 3),
#'                  mu = 1:3,
#'                  sigma = diag(3))
#' 
dmvnormal <- function(x, mu, sigma) {
    .Call('GMCM_dmvnormal', PACKAGE = 'GMCM', x, mu, sigma)
}

rmvnormal <- function(n, mu, sigma) {
    .Call('GMCM_rmvnormal', PACKAGE = 'GMCM', n, mu, sigma)
}

dgmm_loglik <- function(mus, sigmas, pie, z, marginal_loglik) {
    .Call('GMCM_dgmm_loglik', PACKAGE = 'GMCM', mus, sigmas, pie, z, marginal_loglik)
}

dgmm_loglik_marginal <- function(mus, sigmas, pie, z, marginal_loglik) {
    .Call('GMCM_dgmm_loglik_marginal', PACKAGE = 'GMCM', mus, sigmas, pie, z, marginal_loglik)
}

approx_pnorm <- function(z, mu, sd) {
    .Call('GMCM_approx_pnorm', PACKAGE = 'GMCM', z, mu, sd)
}

pgmm_marginal <- function(z, mus, sigmas, pie) {
    .Call('GMCM_pgmm_marginal', PACKAGE = 'GMCM', z, mus, sigmas, pie)
}

EStepRcpp <- function(z, mus, sigmas, pie) {
    .Call('GMCM_EStepRcpp', PACKAGE = 'GMCM', z, mus, sigmas, pie)
}

